#parameters of waveform
name: 'npp_180ns'

#ramsey, T1, rabi, npp, readout, echo, echo_1ax, amplitude
measurement: 'amplitude'

#################################################################################################################################################
#####################################################      writing and sending sequences to AWG      ############################################
#################################################################################################################################################

decimation: 1 #This parameter divides the sampling rate (AWG) by this number.
#Then divides all the other parameters by this number as well.
#assuming decimation = 1 is with 1GS/s. each time unit is 1ns.
#for example, decimation = 2 will divide all the parameters by 2, set the sampling rate to 500MS/s.

#total_wait_time is zero_length * zero_multiple. Time between end of readout to end of pattern
zero_length: 1000 #length of single wait time segment in ns. Minimum length of <~1000
zero_multiple: 2000 #how many times you want to repeat the zero segment

readout_trigger_offset: 800 #number of samples before readout starts that the alazar trigger should be placed


#For most measurements, to get exactly the number of patterns you want,
#(final_sweep_param - initial_sweep_param)/step_size should be an integer.
#otherwise there may be some remainder that gives one more or less pattern.


#Shape should be 'Pulse' or 'Gaussian'

readout:
    readout_duration: 10000
    
npp:
    #amplitude: 1
    nop_p_q_gap: 20 #samples between end of qubit pulse and beginning of readout
    nop_p_q_dur: 10000
    readout_duration: 20000
    ssb_freq: 0.1
    ssb_phase: 90
    shape: 'Pulse'
    
    
amplitude:
    amp_start: 0
    amp_stop: 2
    amp_q_dur: 150
    amp_q_gap: 20
    step: .1
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Gaussian'
    
rabi:
    rabi_pulse_gap: 20 #samples between readout pulse and end of qubit pulse. Does NOT change between patterns
    rabi_pulse_initial_duration: 0 #first duration of qubit pulse
    rabi_pulse_end_duration: 5000 # Rabi length, final duration of qubit pulse (should be larger than initial)
    step: 100
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Gaussian'
    

T1:
    T1_init_gap: 20 #samples between beginning of readout pulse and initial T1 pulse
    T1_final_gap: 1000 #samples between beginning of readout pulse and final T1 pulse
    T1_q_dur: 200 #pulse width of qubit pulse. Does not change between patterns
    step: 20
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Gaussian'

ramsey:
    ramsey_gap_2: 20 #unchanging gap between end of second qubit pulse and beginning of readout
    ramsey_gap_1_init: 0 #initial gap between the two qubit pulses
    ramsey_gap_1_final: 20000 #final gap between the two readout pulses
    ramsey_q_dur: 10000 #size of each individual pulse (i.e. pi/2 pulse)
    step: 400
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Gaussian'

echo:
    echo_gap_2: 20 #gap between last qubit pulse and readout pulse. Does not change by pattern
    #initial should be smaller than final. Gap increases
    echo_initial_t: 20 #inital t gap between first x pulse and y pulse. Or between y pulse and second x pulse
    echo_final_t: 1020 #final t gap
    echo_pi_pulse: 150 #pi pulse used in y pulse and number/2 used in both x pulses
    step: 50
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Gaussian'

    
#This measurement is set up to use a sine wave pulse for the initial pi pulse
#Then use a square pulse to excite the qubit to the second excited state
#So SSB modulation is only used for the first pi pulse

effect_temp:
    ge_first_duration: 260
    ge_second_duration: 260
    rabi_start: 0
    rabi_stop: 1000
    step: 20
    gap_2: 20 #constant gap between third pulse and readout
    gap_1: 20 #constant gap between both (first and second pulse) and (second and third pulse).
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Gaussian'
    
    
    
#################################################################################################################################################
#####################################################      MEASUREMENT (Run Sequence)       #####################################################
#################################################################################################################################################

#inclusive of end points now
#num_patterns will be len(range(q_dur_start, end + step, step))

#running Sequence
pattern_repeat: 1
seq_repeat: 800

#averaging
avg_start: 1000  #The start avraging doesn't need to be changed.
avg_length: 19750

v_threshold: 223.85 #threshold value for distinguishing ground and excited states.
#This value is only used in the fitting scripts. It can be ignored and changed
#In the saved copy as necessary.

#static parameters, these are set before each running of the sequence

set_wr: 7.08434 #7.2025 7.2017
set_wq: 2.9395
set_pr: 15
set_pq: 15
set_q_att: 15
set_r_att: 40 #40 for low power for q4 and 21 for high power 
set_p_twpa: -19.2
set_w_twpa: 8.5689

#################################################################################################################################################
#####################################################      Sweep Parametrs       #####################################################
#################################################################################################################################################



#sweep parameters are frequency ('wr', 'wq') in GHz, power of rf generators ('pr', 'pq') in DBm, and attenuator value ('q_att', 'r_att') in DB
#first letter is w for frequency p for power
#second letter is q for qubit RF generator and r for readout RF
#also p_twpa and w_twpa

#sweep params in GHz or db for attenuator
#If doing a single sweep, will look at p1, double will look at both

#Y axis
p1: 'wq' #7.1486 +- 2 MHz
p1start: 3.267
p1stop: 3.269
p1step: .00006

#x axis
p2: 'q_att'
p2start: 5
p2stop: 15
p2step: 1



#TWPA params:
#8.2893
#-19.2

#-18.6
#8.2952

#-19.58


