#parameters of waveform
name: 'Res Spec'

#ramsey, T1, rabi, npp, readout, echo, echo_1ax, amplitude
measurement: 'npp'

decimation: 1 #This parameter divides the sampling rate by this number.
#Then divides all the other parameters by this number as well.
#assuming decimation = 1 is with 1GS/s. each time unit is 1ns.
#for example, decimation = 2 will divide all the parameters by 2, set the sampling rate to 500MS/s.

#total_wait_time is zero_length * zero_multiple. Time between end of readout to end of pattern
zero_length: 1000 #length of single wait time segment in ns. Minimum length of <~1000
zero_multiple: 2000 #how many times you want to repeat the zero segment


#For most measurements, to get exactly the number of patterns you want,
#(final_sweep_param - initial_sweep_param)/step_size should be an integer.
#otherwise there may be some remainder that gives one more or less pattern.

npp:
    nop_p_q_gap: 20 #samples between end of qubit pulse and beginning of readout
    nop_p_q_dur: 150
    readout_duration: 50000

amplitude:
    amp_start: 0
    amp_stop: 2
    amp_q_dur: 150
    amp_q_gap: 20
    step: .1
    readout_duration: 20000
    
rabi:
    rabi_pulse_gap: 20 #samples between readout pulse and end of qubit pulse. Does NOT change between patterns
    rabi_pulse_initial_duration: 0 #first duration of qubit pulse
    rabi_pulse_end_duration: 800 #final duration of qubit pulse (should be larger than initial)
    step: 16
    readout_duration: 60000

T1:
    T1_init_gap: 20 #samples between beginning of readout pulse and initial T1 pulse
    T1_final_gap: 500020 #samples between beginning of readout pulse and final T1 pulse
    T1_q_dur: 150 #pulse width of qubit pulse. Does not change between patterns
    step: 25000
    readout_duration: 20000

ramsey:
    ramsey_gap_2: 20 #unchanging gap between end of second qubit pulse and beginning of readout
    ramsey_gap_1_init: 0 #initial gap between the two qubit pulses
    ramsey_gap_1_final: 60000 #final gap between the two readout pulses
    ramsey_q_dur: 75 #size of each individual pulse (i.e. pi/2 pulse)
    step: 1200
    readout_duration: 20000

echo:
    echo_gap_2: 20 #gap between last qubit pulse and readout pulse. Does not change by pattern
    
    #initial should be smaller than final. Gap increases
    echo_initial_t: 20 #inital t gap between first x pulse and y pulse. Or between y pulse and second x pulse
    echo_final_t: 600020 #final t gap
    echo_pi_pulse: 150 #pi pulse used in y pulse and number/2 used in both x pulses
    step: 12000
    readout_duration: 20000

#inclusive of end points now
#num_patterns will be len(range(q_dur_start, end + step, step))

#running parameters
pattern_repeat: 1
seq_repeat: 2000

#averaging

#wave must be re-sent after changing this
#not sure it works as of now
readout_trigger_offset: 800 #number of samples before readout starts that the alazar trigger should be placed

avg_start: 1000
avg_length: 49750

v_threshold: 223.85 #threshold value for distinguishing ground and excited states.
#This value is only used in the fitting scripts. It can be ignored and changed
#In the saved copy as necessary.

#sweep parameters are frequency ('wr', 'wq') in GHz, power of rf generators ('pr', 'pq') in DBm, and attenuator value ('q_att', 'r_att') in DB
#first letter is w for frequency p for power
#second letter is q for qubit RF generator and r for readout RF
#also p_twpa and w_twpa

#sweep params in GHz or db for attenuator
#If doing a single sweep, will look at p1, double will look at both

#Y axis
p1: 'wq' #7.1486 +- 2 MHz
p1start: 3.2177
p1stop: 3.2176
p1step: .00001

#x axis
p2: 'pr'
p2start: 13
p2stop: 17
p2step: .5

#static parameters, set before each running of the sequence

set_wr: 7.1486 #7.1486 7.1478
#set_wr_offset: 0.1
set_wq: 3.2176
set_wq_offset: 0.1

set_pr: 16 # 15, 13.5
set_pq: 15
set_q_att: 20
set_r_att: 41 #40, 22
set_p_twpa: -19.2
set_w_twpa: 8.5689

#TWPA params:
#8.2893
#-19.2

#-18.6
#8.2952

#-19.58


