name: 'name'

measurement: 'sbb_phase_sweep'

decimation: 1 #This parameter divides the sampling rate (AWG) by this number.
#Then divides all the other parameters by this number as well.
#assuming decimation = 1 is with 1GS/s. each time unit is 1ns.
#for example, decimation = 2 will divide all the parameters by 2, set the sampling rate to 500MS/s.

#This must be changed when going above 300us 100pt T1 measurements. Roughly

#total_wait_time is zero_length * zero_multiple. Time between end of readout to end of pattern
zero_length: 1000 #length of single wait time segment in ns. Minimum length of <~1000
zero_multiple: 2000 #how many times you want to repeat the zero segment

readout_trigger_offset: 800 #number of samples before readout starts that the alazar trigger should be placed


############################################### Measurement Type ##########################################
single_pulse:
    gap: 20 #samples between end of qubit pulse and beginning of readout
    duration: 10000
    readout_duration: 20000
    ssb_freq: 0.01
    ssb_phase: -90
    shape: 'Pulse'

amplitude:
    amp_start: .75
    amp_stop: 1.75
    amp_q_dur: 175
    amp_q_gap: 20
    step: .02
    readout_duration: 20000
    ssb_freq: 0
    ssb_phase: 90
    shape: 'Pulse'

sbb_freq_sweep:
    gap: 20 #samples between end of qubit pulse and beginning of readout
    duration: 10000
    readout_duration: 20000
    ssb_freq_start: 0.001
    ssb_freq_end: 0.02
    ssb_freq_step: 0.001
    ssb_phase: -90
    shape: 'Pulse'
  
sbb_phase_sweep:
    gap: 20 #samples between end of qubit pulse and beginning of readout
    duration: 10000
    readout_duration: 20000
    ssb_freq: 0.001
    ssb_phase_start: 0
    ssb_phase_end: 90
    ssb_phase_step: 3
    shape: 'Pulse'

#################################################################################################################################################
#####################################################      MEASUREMENT (Run Sequence)       #####################################################
#################################################################################################################################################

pattern_repeat: 1
seq_repeat: 1000

#averaging
avg_start: 1000  #The start avraging doesn't need to be changed.
avg_length: 19750

v_threshold: 223.85 #threshold value for distinguishing ground and excited states.S
#This value is only used in the fitting scripts. It can be ignored and changed
#In the saved copy as necessary.

#static parameters, these are set before each running of the sequence

set_wr: 7.148291
set_wq: 3.3144648742 #3.1685813
set_wef: 3.0962426

set_pr: 15
set_pq: 15
set_pwef: 15

set_r_att: 30 #40 for low power for q4 and 21 for high power 
set_q_att: 6
set_p_twpa: -19.7 #-18.9
set_w_twpa: 8.4055 #8.5035

#################################################################################################################################################
#####################################################      Sweeps       #########################################################################
#################################################################################################################################################
p1: 'q_att'
p1start: 0
p1stop: 30
p1step: 1